version: 2
snapshot:
  widths:
    - 360
    - 768
    - 1280
    - 1366
    - 1920
  minHeight: 1024
  percyCSS: ""
discovery:
  allowedHostnames: []
  networkIdleTimeout: 100
static:
  cleanUrls: false
upload:
  files: "**/*.{png,jpg,jpeg,svg}"
  ignore: ""
  stripExtensions: false
