version: 2

defaults: &defaults
  working_directory: ~/repo
  docker:
      - image: circleci/node:10.16

jobs:
  install:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
          - v2-dependencies-{{ checksum "yarn.lock" }}
          - v2-dependencies-
      - run: yarn install --frozen-lockfile
      - save_cache:
          paths:
            - ./node_modules
          key: v2-dependencies-{{ checksum "yarn.lock" }}
      - persist_to_workspace:
          root: ~/repo
          paths:
            - ./

  build:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run: yarn build
      - persist_to_workspace:
          root: ~/repo
          paths:
            - ./
  test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run: yarn test --maxWorkers=2
  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Set registry URL
          command: npm set registry https://packagecloud.io/@logcomex/design/npm/
      - run:
          name: Authenticate with registry
          command: echo "//packagecloud.io/@logcomex/design/npm/:_authToken=$NPM_TOKEN" > ~/repo/.npmrc
      - run:
          name: Connect to host
          command: yarn release

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - install
      - test:
          requires:
            - install
      - build:
          requires:
              - install
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
