name: npm-publish-beta
on:
  push:
    branches:
      - homol
jobs:
  publish:
    name: Build & Publish
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.RELEASE_PERSONAL_TOKEN }}
    - name: Setting Node version to ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        registry-url: 'https://registry.npmjs.org'
    - uses: oleksiyrudenko/gha-git-credentials@v2-latest
      with:
        token: '${{ secrets.RELEASE_PERSONAL_TOKEN }}'
    - name: Caching node_modules
      id: cache-modules
      uses: actions/cache@v1
      with:
        path: node_modules
        key: ${{ matrix.node-version }}-${{ runner.OS }}-build-${{ hashFiles('package.json', 'yarn.lock') }}
    - name: Installing dependencies
      run: yarn install
    - name: Building
      run: yarn build
    - name: Publishing library
      run: npm run release-beta
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.RELEASE_PERSONAL_TOKEN }}
    - name: Updating Percy baseline
      run: yarn snapshot
      env:
        PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
