name: npm-publish-beta
on:
  push:
    branches:
      - homol
jobs:
  publish:
    name: Build & Publish
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    if: github.event_name == 'push' && github.ref == 'refs/heads/homol'
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        registry-url: 'https://registry.npmjs.org'
    - uses: oleksiyrudenko/gha-git-credentials@v2-latest
      with:
        token: '${{ secrets.RELEASE_PERSONAL_TOKEN }}'
    - name: Cache node_modules
      id: cache-modules
      uses: actions/cache@v1
      with:
        path: node_modules
        key: 12.x-${{ runner.OS }}-build-${{ hashFiles('package.json') }}
    - name: Install
      run: yarn
    - name: Build
      run: yarn build
    - name: Publish library
      run: export AWS_ACCESS_KEY_ID=${RELEASE_PERSONAL_TOKEN} && npm run release
      env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
          RELEASE_PERSONAL_TOKEN: ${{ secrets.RELEASE_PERSONAL_TOKEN }}
