name: npm-publish
on:
  push:
    branches:
      - master
jobs:
  publish:
    name: Build & Publish
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    steps:
    - uses: actions/checkout@v2
    - name: Setting Node version to ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    # TODO: Validar o porquê do cache ter sido removido
    # - name: Cache node_modules
    #   id: cache-modules
    #   uses: actions/cache@v1
    #   with:
    #     path: node_modules
    #     key: ${{ matrix.node-version }}-${{ runner.OS }}-build-${{ hashFiles('package.json', 'yarn.lock') }}
    - name: Installing dependencies
      run: yarn install
    - name: Unit testing
      run: yarn test
    - name: Building
      run: yarn build
    - name: Publishing library
      uses: mikeal/merge-release@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
